### ISSUE TITLE
Language Pack/Font?

### ISSUE THREAD

**Issue by versipellis** [zhuojg/chinese-calligraphy-dataset#2]
Hi there, I'm struggling to get the folder and filenames in the zip file to display properly. What language pack and/or fonts are being used? I have the language pack installed properly and other files on my system display the Chinese characters fine, but the zip file's contents are garbled for me.

![image](https://user-images.githubusercontent.com/6579034/198851385-6b6aa77f-9fb4-47fa-ad96-a294c50f96e0.png)

**Comment by zhuojg** [comment]
I think the first thing you can try is to use third-party software (like 7-zip, bandizip) to unzip the file.

**Comment by versipellis** [comment]
Just tried this with 7zip, still no luck.

![image](https://user-images.githubusercontent.com/6579034/198870410-60f6dfc8-ab85-4a49-9f68-b21ca3af6310.png)

**Comment by zhuojg** [comment]
> Just tried this with 7zip, still no luck.
> 
> ![image](https://user-images.githubusercontent.com/6579034/198870410-60f6dfc8-ab85-4a49-9f68-b21ca3af6310.png)

I guess the problem was caused by the default encoding setting on Windows, which is GBK on my windows computer and I think this is not the same on yours.

I am not very sure about the solutions, but there is something you can try:

- Use the new zip files. The new files are generated on macOS, and encoding problem should be fixed.
  - link for the first dataset (character as top level): https://drive.google.com/file/d/1k849yUZhkUfbupZT0kRR2ZzZj5g89yLw/view?usp=sharing
  - link for the second dataset (calligrapher as top level): https://drive.google.com/file/d/10QJrw0Qdk4O1bIrehCLmdiCkwpLbGVe8/view?usp=share_link
- Changing encoding in the archiver (only for bandizip because 7-zip does not support it). You can change it by clicking this button in the software and choose `Chinese Simplified`:
![Snipaste_2022-10-30_20-15-25](https://user-images.githubusercontent.com/24386525/198878130-a5e635f3-5d64-46d6-82dd-a0e9d9818305.png)

**Comment by versipellis** [comment]
Looks like re-encoding it via macOS did the trick, the new zip file from Google drive works! Thank you very much @zhuojg!
